# Generated by Django 5.1 on 2024-08-22 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={"verbose_name": "дом", "verbose_name_plural": "дома"},
        ),
    ]
