# Generated by Django 5.1 on 2024-08-23 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0002_alter_house_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": ["name"],
                "verbose_name": "дом",
                "verbose_name_plural": "дома",
            },
        ),
    ]
