# Generated by Django 5.1 on 2024-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0003_alter_house_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="houses/photos",
                verbose_name="фотография",
            ),
        ),
    ]
